name: chill_guide
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  http: ^1.2.1
  intl: ^0.19.0
  meta: ^1.11.0
  package_info_plus: ^7.0.0
  riverpod_annotation: ^2.3.5
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  skeletonizer: ^1.1.1
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  choco_lints:
    git:
      ref: 1.1.0
      url: git@github.com:charlescyt/choco_lints.git
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.5.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
